services:
  # 1. LA BASE DE DATOS
  db-mysql:
    image: mysql:8.0
    container_name: techshop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techshop_db
    ports:
      - "3306:3306"

  # 2. EL BACKEND (Ya lo construiste en el disco D)
  backend-api:
    image: techshop-backend
    container_name: techshop-api
    depends_on:
      - db-mysql
    ports:
      - "8080:8080"


    environment:
      # Añadimos parámetros de reconexión a la URL
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/techshop_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    # Esto hará que si el backend falla porque la DB no está lista, Docker lo reviva
    restart: on-failure

  # 3. EL FRONTEND (Ya lo construiste en el disco C)
  frontend-web:
    image: techshop-frontend
    container_name: techshop-web
    depends_on:
      - backend-api
    ports:
      - "81:80"
